### ISSUE TITLE
Failed Renders using Alternate Wavtools

### ISSUE THREAD

**Issue by etonzolo** [stakira/OpenUtau#1842]
### Acknowledgement

- [x] I have read Getting-Started and FAQ
- [x] If dealing with version 0.1.549 or higher, you have installed the .NET 8 runtime

### 🐛 Describe the bug

Setting OpenUtau to use any non-default wavtool render causes a "Failed to Render" playback error, despite Simple and Convergence wavtools working as intended. This issue seems to persist regardless of project, singer, or wavtool used.

### Explains how to reproduce the bug

1. Open either a new or existing project in OpenUtau 0.1.565.0
2. With any Singer on Classic mode; set the Wavtool to any non-default one (i've tested w/ both moresampler and wavtool64)
3. Attempt playback of notes as normal
4. Failed to render error shows up

### OS & Version

Debian 12 using Wine 10.0

### Logs

[log20251123.txt](https://github.com/user-attachments/files/23698270/log20251123.txt)

<img width="85%" alt="Screenshot of OpenUtau and Debug screen with the Wavtool set to Convergence" src="https://github.com/user-attachments/assets/3dc27f37-4ccd-4b5e-8986-0a39ba8d3d96" />
<img width="85%" alt="Screenshot of OpenUtau and Debug screen with the Wavtool set to moresampler" src="https://github.com/user-attachments/assets/61dad3eb-2209-45f7-ae97-7922de4fad22" />

**Comment by BagelHero** [comment]
```C#
2025-11-23 14:34:02.005 -05:00 [ERR] Failed to pre-render.
System.AggregateException: One or more errors occurred. (An error occurred trying to start process '/home/---/.cache/OpenUtau/temp.bat' with working directory '/home/---/.cache/OpenUtau'. Permission denied)
 ---> System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/home/---/.cache/OpenUtau/temp.bat' with working directory '/home/---/.cache/OpenUtau'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at OpenUtau.Core.Util.ProcessRunner.Run(String file, String args, ILogger logger, String workDir, Int32 timeoutMs) in /home/runner/work/OpenUtau/OpenUtau/OpenUtau.Core/Util/ProcessRunner.cs:line 36
   at OpenUtau.Classic.ExeWavtool.Concatenate(List`1 resamplerItems, String tempPath, CancellationTokenSource cancellation) in /home/runner/work/OpenUtau/OpenUtau/OpenUtau.Core/Classic/ExeWavtool.cs:line 61
   at OpenUtau.Classic.ClassicRenderer.<>c__DisplayClass9_0.<RenderExternal>b__0() in /home/runner/work/OpenUtau/OpenUtau/OpenUtau.Core/Classic/ClassicRenderer.cs:line 122
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OpenUtau.Core.Render.RenderEngine.RenderRequests(RenderPartRequest[] requests, CancellationTokenSource cancellation, Boolean playing) in /home/runner/work/OpenUtau/OpenUtau/OpenUtau.Core/Render/RenderEngine.cs:line 243
   at OpenUtau.Core.Render.RenderEngine.<>c__DisplayClass8_0.<PreRenderProject>b__0() in /home/runner/work/OpenUtau/OpenUtau/OpenUtau.Core/Render/RenderEngine.cs:line 173
```

So, this is expected for Linux until a certain version (its an issue with compatibility as they rely on .bat files), but it should be fixed now as I understand it? So it's strange that it's happening on latest. You have Wine set up in Preferences I assume?

**Comment by etonzolo** [comment]
> So, this is expected for Linux until a certain version (its an issue with compatibility as they rely on .bat files), but it should be fixed now as I understand it? So it's strange that it's happening on latest. You have Wine set up in Preferences I assume?

Yes, I currently have that set-up, and if I recall correctly had tried both with and without it. It doesn't seem to make any difference.

Though, if this was a known issue in some past versions, Is it possible someting in the update may have gone wrong with those files (particularly since I updated from 1.529.0 direct which I think I remember seeing mentioned in a different bug thread)?

**Comment by BagelHero** [comment]
I think the relevant PRs are these... https://github.com/stakira/OpenUtau/pull/1571 / https://github.com/stakira/OpenUtau/pull/1586 

As you can see, it _should_ be fixed. For troubleshooting... I would first try downloading a fresh copy of OpenUtau 0.1.565 and see if it works any differently. If not, then we can at least rule out an upgrade issue. Your resamplers all work as expected, right? It's just wavtools?

**Comment by atouu** [comment]
By the looks of it, you're still using a wrapper which is no longer necessary (and no longer work in latest versions). You need to set wine path in settings then choose `moresampler.exe` instead.

![Image](https://github.com/user-attachments/assets/606f106a-4cfc-4909-859a-e111b9873dd2)

**Comment by etonzolo** [comment]
> By the looks of it, you're still using a wrapper which is no longer necessary (and no longer work in latest versions). You need to set wine path in settings then choose `moresampler.exe` instead.
> 
> [ ](https://private-user-images.githubusercontent.com/67765922/518515023-606f106a-4cfc-4909-859a-e111b9873dd2.gif?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ1MjgzOTAsIm5iZiI6MTc2NDUyODA5MCwicGF0aCI6Ii82Nzc2NTkyMi81MTg1MTUwMjMtNjA2ZjEwNmEtNGNmYy00OTA5LTg1OWEtZTExMWI5ODczZGQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTMwVDE4NDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZDNjOTQzY2UzOWZmOWQyMDBjNjQwMzIyMTY4MTA2ZmQ0MTE5M2I3MzUxMWQzZjQzMDc5NTA3ZDcxYjdkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lRiIvXoHvsmmYZrdnUZWLFzWwo0TA1isYGIgkjY_x6w) ![Image](https://private-user-images.githubusercontent.com/67765922/518515023-606f106a-4cfc-4909-859a-e111b9873dd2.gif?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ1MjgzOTAsIm5iZiI6MTc2NDUyODA5MCwicGF0aCI6Ii82Nzc2NTkyMi81MTg1MTUwMjMtNjA2ZjEwNmEtNGNmYy00OTA5LTg1OWEtZTExMWI5ODczZGQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTMwVDE4NDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZDNjOTQzY2UzOWZmOWQyMDBjNjQwMzIyMTY4MTA2ZmQ0MTE5M2I3MzUxMWQzZjQzMDc5NTA3ZDcxYjdkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lRiIvXoHvsmmYZrdnUZWLFzWwo0TA1isYGIgkjY_x6w) [ ](https://private-user-images.githubusercontent.com/67765922/518515023-606f106a-4cfc-4909-859a-e111b9873dd2.gif?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ1MjgzOTAsIm5iZiI6MTc2NDUyODA5MCwicGF0aCI6Ii82Nzc2NTkyMi81MTg1MTUwMjMtNjA2ZjEwNmEtNGNmYy00OTA5LTg1OWEtZTExMWI5ODczZGQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTMwVDE4NDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZDNjOTQzY2UzOWZmOWQyMDBjNjQwMzIyMTY4MTA2ZmQ0MTE5M2I3MzUxMWQzZjQzMDc5NTA3ZDcxYjdkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lRiIvXoHvsmmYZrdnUZWLFzWwo0TA1isYGIgkjY_x6w)

I tried this as soon as a specific `moresampler.exe` showed up the day after i send the intial report, and it didn't appear to change anything. I was still getting the same errors as before.

> I think the relevant PRs are these... [#1571](https://github.com/stakira/OpenUtau/pull/1571) / [#1586](https://github.com/stakira/OpenUtau/pull/1586)
> 
> As you can see, it _should_ be fixed. For troubleshooting... I would first try downloading a fresh copy of OpenUtau 0.1.565 and see if it works any differently. If not, then we can at least rule out an upgrade issue. Your resamplers all work as expected, right? It's just wavtools?

Yes my resamplers are working perfectly fine, it was just the wavtools that had issues. Attempting a clean install does seem to have fixed the issue, though!

Thank you both so much for the help. I don't know what went wrong the first time or why i didn't think to clean install myself, but I very much appraciate the attempts to figure this out.
